// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqKjKDtVvSdeCdkms6xgJlybPWQjDncY',
    appId: '1:70935208541:web:505066102da89c640f63b4',
    messagingSenderId: '70935208541',
    projectId: 'nextstepp-c7a1e',
    authDomain: 'nextstepp-c7a1e.firebaseapp.com',
    storageBucket: 'nextstepp-c7a1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDwTfTmyxv3Yt4GW0LezdduqhwBtsFZ4',
    appId: '1:70935208541:android:5287f19ccf074ac00f63b4',
    messagingSenderId: '70935208541',
    projectId: 'nextstepp-c7a1e',
    storageBucket: 'nextstepp-c7a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-30zJk_qmv5b8j4CuV8f0mIrAiJqZO4',
    appId: '1:70935208541:ios:190ed0ede7cadffe0f63b4',
    messagingSenderId: '70935208541',
    projectId: 'nextstepp-c7a1e',
    storageBucket: 'nextstepp-c7a1e.firebasestorage.app',
    iosBundleId: 'com.example.nextStepp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-30zJk_qmv5b8j4CuV8f0mIrAiJqZO4',
    appId: '1:70935208541:ios:190ed0ede7cadffe0f63b4',
    messagingSenderId: '70935208541',
    projectId: 'nextstepp-c7a1e',
    storageBucket: 'nextstepp-c7a1e.firebasestorage.app',
    iosBundleId: 'com.example.nextStepp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqKjKDtVvSdeCdkms6xgJlybPWQjDncY',
    appId: '1:70935208541:web:55e8bce42b5fa1310f63b4',
    messagingSenderId: '70935208541',
    projectId: 'nextstepp-c7a1e',
    authDomain: 'nextstepp-c7a1e.firebaseapp.com',
    storageBucket: 'nextstepp-c7a1e.firebasestorage.app',
  );
}
